# Generated by Django 4.2.11 on 2024-04-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoria_libro_delete_usuario_delete_usuarioadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='codigo_isbn',
            field=models.CharField(max_length=300),
        ),
    ]
