# Generated by Django 4.2.11 on 2024-04-10 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_libro_codigo_isbn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300, unique=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='categoria/')),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.CharField(max_length=300)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='juego/')),
                ('categoria_juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juegos', to='core.categoria')),
            ],
        ),
    ]
