# Generated by Django 4.2.11 on 2024-04-10 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_categoria_juego_juego'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='categoria_juego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juegos', to='core.categoria_juego'),
        ),
    ]
