# Generated by Django 4.2.11 on 2024-04-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_juego_categoria_juego'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='categoria_juego',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='categoriaJuego/'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Libro',
        ),
    ]
