# Generated by Django 4.2.11 on 2024-04-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_libro_categoria_alter_categoria_juego_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria_juego',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='categoria/'),
        ),
    ]
